### ISSUE TITLE
ValueError: 9 is not a valid PenColor

### ISSUE THREAD

**Issue by Utopiah** [ricklupton/rmc#17]
Trying to convert from reMarkable Pro with highlights in color

**Comment by Azeirah** [comment]
Yep! This is a solved issue, but it hasn't been merged yet by @ricklupton 

https://github.com/ricklupton/rmscene/pull/31

**Comment by Utopiah** [comment]
As `rmscene` was released as v0.6.0 does the pipx install take that into account (didn't seem to) and if not, is there is way to force the upgrade?

**Comment by Seb-sti1** [comment]
The released version of `rmc` currently uses `rmscene = ">=0.1.0, <0.3.0"` ([see pyproject.toml#L10](https://github.com/ricklupton/rmc/blob/main/pyproject.toml#L10)) so pipx mostly likely installs the 0.2.0.

There are some PRs to update `rmc` so that it can use a newer version of `rmscene` but it's still in the PR state for now :)

**Comment by Utopiah** [comment]
Thanks for the clarification. I'd argue it'd be great to go through those PRs because basically right now reMarkable Pro notes can't be exporter anymore, at least not while using (some) colors.

**Comment by Seb-sti1** [comment]
Yes, it's on its way (but it will probably take some time). In the meantime, you can try https://github.com/ricklupton/rmc/pull/18 (probably the best if you want colour) or https://github.com/ricklupton/rmc/pull/19 (doesn't support the new remarkable file features added by https://github.com/ricklupton/rmscene/pull/31).

**Comment by Seb-sti1** [comment]
@Utopiah could you try on the current version of master? Both #18 and #19 were merged by Rick Lupton

**Comment by ricklupton** [comment]
And now released as v0.2.0 ... hopefully that works with your files now.

**Comment by Seb-sti1** [comment]
I was so confused at first, but everything is okay: it was fixed in https://github.com/ricklupton/rmscene/pull/36 but this is not released yet.

You can "cheat" by doing `pip uninstall rmscene` and then using the main branch of rmscene with `pip install git+https://github.com/ricklupton/rmscene.git`. With this, I was able to export the svg for your file!

**Comment by Utopiah** [comment]
Yeay, colors, thank you all!
